// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IODummyFactory.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.IO.Test source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.IO.Test
{
    using global::System;

    using FakeItEasy;

    using OBeautifulCode.AutoFakeItEasy;

    /// <summary>
    /// A Dummy Factory for types in <see cref="OBeautifulCode.IO"/>.
    /// </summary>
#if !OBeautifulCodeIOSolution
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.IO.Test", "See package version number")]
    internal
#else
    public
#endif
    class IODummyFactory : DefaultIODummyFactory
    {
        public IODummyFactory()
        {
            /* Add any overriding or custom registrations here. */
            AutoFixtureBackedDummyFactory.ConstrainDummyToExclude(FileFormat.Unspecified);
        }
    }
}