// --------------------------------------------------------------------------------------------------------------------
// <copyright file="FileMergeHeaderTreatment.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.IO.Recipes source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.IO.Recipes
{
    /// <summary>
    /// Determines what to do with the header line of the bottom file when merging two files.
    /// </summary>
#if !OBeautifulCodeIOSolution
    [global::System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.IO.Recipes", "See package version number")]
    internal
#else
    public
#endif
    enum FileMergeHeaderTreatment
    {
        /// <summary>
        /// Delete the header of the bottom file
        /// </summary>
        DeleteBottomFileHeader,

        /// <summary>
        /// keep the header of the bottom file (i.e. take the file completely as-is)
        /// </summary>
        KeepBottomFileHeader,
    }
}
