// --------------------------------------------------------------------------------------------------------------------
// <copyright file="FileHelper.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.IO.Recipes source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.IO.Recipes
{
    using global::System.Collections.Generic;

    /// <summary>
    /// Provides various convenience methods for dealing with files.
    /// </summary>
#if !OBeautifulCodeIOSolution
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.IO.Recipes", "See package version number")]
    internal
#else
    public
#endif
    static partial class FileHelper
    {
        /// <summary>
        /// Lock object for creating temporary resources.
        /// </summary>
        private static readonly object CreateTemporaryResourceLock = new object();

        /// <summary>
        /// Tokens that are restricted from being included in files.
        /// </summary>
        private static readonly HashSet<string> RestrictedFileNameTokens = new HashSet<string> { "CON", "PRN", "AUX", "CLOCK$", "NUL", "COM0", "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8", "COM9", "LPT0", "LPT1", "LPT2", "LPT3", "LPT4", "LPT5", "LPT6", "LPT7", "LPT8", "LPT9" };
    }
}